language: go
sudo: false
go:
  - 1.5
  - 1.6
  - 1.7
install:
  - go get -u -v github.com/nsf/gocode
  - go get -u -v github.com/rogpeppe/godef
  - go get -u -v github.com/golang/lint/golint
  - go get -u -v github.com/lukehoban/go-outline
  - go get -u -v sourcegraph.com/sqs/goreturns
  - go get -u -v golang.org/x/tools/cmd/gorename
  - go get -u -v github.com/tpng/gopkgs
  - go get -u -v github.com/newhook/go-symbols
  - go get -u -v golang.org/x/tools/cmd/guru
  - go get -u -v github.com/cweill/gotests/...
  - go get -u -t github.com/onsi/ginkgo
  - go get -u -t github.com/onsi/gomega  
